title: Planet of the Apes media franchise {
  near: top-center
  shape: text
  style: {
    font-size: 29
    bold: true
    underline: true
  }
}

Battle -> for
Beneath -> the
Escape -> from
of -> the
from -> the
for -> the
Conquest -> of
the -> Planet of the Apes

Rise -> of
Dawn -> of
War -> for
Kingdom -> of
Return -> to
to -> the
